"""create recommendations table

Revision ID: 02cb09c44e0c
Revises: 6a31027bf232
Create Date: 2026-08-24 18:52:59.107302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02cb09c44e0c'
down_revision: Union[str, Sequence[str], None] = '6a31027bf232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_approval_status', 'recommendations', ['approval_status'], unique=False)
    op.create_index('ix_recommendations_incident_created_at', 'recommendations', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_incident_id'), 'recommendations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recommendations_investigation_id'), 'recommendations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_recommendations_merchant_id'), 'recommendations', ['merchant_id'], unique=False)
    op.create_index('ix_recommendations_merchant_status', 'recommendations', ['merchant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_merchant_status', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_merchant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_investigation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_incident_id'), table_name='recommendations')
    op.drop_index('ix_recommendations_incident_created_at', table_name='recommendations')
    op.drop_index('ix_recommendations_approval_status', table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
