"""link recommendation approver user

Revision ID: 5e3bf713ec7f
Revises: d999118d15a5
Create Date: 2026-08-24 19:01:21.348980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3bf713ec7f'
down_revision: Union[str, Sequence[str], None] = 'd999118d15a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_recommendations_approved_by_user_id'), 'recommendations', ['approved_by_user_id'], unique=False)
    op.create_foreign_key('fk_recommendations_approved_by_user_id_users', 'recommendations', 'users', ['approved_by_user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recommendations_approved_by_user_id_users', 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_approved_by_user_id'), table_name='recommendations')
    op.drop_column('recommendations', 'approved_by_user_id')
    # ### end Alembic commands ###
