"""store investigation uncertainty as jsonb

Revision ID: 6418a45015ee
Revises: fc7e3d85570d
Create Date: 2026-08-27 16:37:39.619694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6418a45015ee'
down_revision: Union[str, Sequence[str], None] = 'fc7e3d85570d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investigations",
        "uncertainty",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using=(
            "CASE WHEN uncertainty IS NULL THEN NULL "
            "ELSE jsonb_build_object('legacy_text', uncertainty) END"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "investigations",
        "uncertainty",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using="uncertainty::text",
    )
    # ### end Alembic commands ###
