"""create investigations table

Revision ID: 6a31027bf232
Revises: ef3a8c0896ea
Create Date: 2026-08-24 18:47:55.221535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a31027bf232'
down_revision: Union[str, Sequence[str], None] = 'ef3a8c0896ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_incident_created_at', 'investigations', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_incident_id'), 'investigations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigations_merchant_id'), 'investigations', ['merchant_id'], unique=False)
    op.create_index('ix_investigations_merchant_status', 'investigations', ['merchant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investigations_merchant_status', table_name='investigations')
    op.drop_index(op.f('ix_investigations_merchant_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_incident_id'), table_name='investigations')
    op.drop_index('ix_investigations_incident_created_at', table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
