"""create incidents table

Revision ID: ef3a8c0896ea
Revises: b718ad216762
Create Date: 2026-08-24 18:43:33.953461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3a8c0896ea'
down_revision: Union[str, Sequence[str], None] = 'b718ad216762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('baseline_failure_rate', sa.Float(), nullable=True),
    sa.Column('current_failure_rate', sa.Float(), nullable=True),
    sa.Column('affected_transactions', sa.Integer(), nullable=False),
    sa.Column('failed_transactions', sa.Integer(), nullable=False),
    sa.Column('revenue_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_detected_at'), 'incidents', ['detected_at'], unique=False)
    op.create_index('ix_incidents_merchant_detected_at', 'incidents', ['merchant_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_merchant_id'), 'incidents', ['merchant_id'], unique=False)
    op.create_index('ix_incidents_merchant_status', 'incidents', ['merchant_id', 'status'], unique=False)
    op.create_index('ix_incidents_type_severity', 'incidents', ['incident_type', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_type_severity', table_name='incidents')
    op.drop_index('ix_incidents_merchant_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_merchant_id'), table_name='incidents')
    op.drop_index('ix_incidents_merchant_detected_at', table_name='incidents')
    op.drop_index(op.f('ix_incidents_detected_at'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
