"""scope transaction idempotency by merchant

Revision ID: fc7e3d85570d
Revises: 5e3bf713ec7f
Create Date: 2026-08-24 19:39:11.316570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7e3d85570d'
down_revision: Union[str, Sequence[str], None] = '5e3bf713ec7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_transactions_provider_payment_id'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_transactions_merchant_provider_payment_id', 'transactions', ['merchant_id', 'provider', 'provider_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_merchant_provider_payment_id', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_transactions_provider_payment_id'), 'transactions', ['provider', 'provider_payment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
