# PayGuard AI Risk Engine v1 configuration.
# Keep deterministic thresholds centralized here.

RULE_VERSION = 1

# Amount rules
MIN_CUSTOMER_HISTORY_COUNT = 5
HIGH_AMOUNT_MULTIPLIER = 5
EXTREME_AMOUNT_MULTIPLIER = 10

# Velocity rules
HIGH_VELOCITY_THRESHOLD = 5
EXTREME_VELOCITY_THRESHOLD = 10

# Repeated failure rules
HIGH_FAILURE_THRESHOLD = 4
EXTREME_FAILURE_THRESHOLD = 8

# Device rules
DEVICE_MULTI_CUSTOMER_THRESHOLD = 5
DEVICE_EXTREME_MULTI_CUSTOMER_THRESHOLD = 10

# Historical customer risk
HIGH_CUSTOMER_RISK_THRESHOLD = 70
EXTREME_CUSTOMER_RISK_THRESHOLD = 85

# Infrastructure rules
BANK_FAILURE_MULTIPLIER = 2
BANK_EXTREME_FAILURE_MULTIPLIER = 4
BANK_MIN_SAMPLE_SIZE = 20
METHOD_FAILURE_MULTIPLIER = 3
METHOD_MIN_SAMPLE_SIZE = 30
MERCHANT_FAILURE_MULTIPLIER = 3
MERCHANT_MIN_SAMPLE_SIZE = 30
REFUND_FAILURE_MULTIPLIER = 3
REFUND_MIN_SAMPLE_SIZE = 30

# Duplicate payment pattern
DUPLICATE_PAYMENT_COUNT = 3
DUPLICATE_PAYMENT_WINDOW_SECONDS = 30
