from enum import StrEnum


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RuleGroup(StrEnum):
    AMOUNT = "AMOUNT"
    VELOCITY = "VELOCITY"
    FAILURE = "FAILURE"
    DEVICE = "DEVICE"
    LOCATION = "LOCATION"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    REFUND = "REFUND"
    DUPLICATE = "DUPLICATE"
    HISTORICAL = "HISTORICAL"


RULE_SCORE_CAP = 70
ANOMALY_SCORE_CAP = 20
CONTEXTUAL_SCORE_CAP = 10
TOTAL_SCORE_CAP = 100

RISK_MODEL_VERSION = "risk-v1"


class RuleCode(StrEnum):
    HIGH_AMOUNT = "HIGH_AMOUNT"
    EXTREME_AMOUNT = "EXTREME_AMOUNT"
    HIGH_VELOCITY = "HIGH_VELOCITY"
    EXTREME_VELOCITY = "EXTREME_VELOCITY"
    REPEATED_FAILURES = "REPEATED_FAILURES"
    NEW_DEVICE = "NEW_DEVICE"
    DEVICE_MULTI_CUSTOMER = "DEVICE_MULTI_CUSTOMER"
    NEW_LOCATION = "NEW_LOCATION"
    RAPID_LOCATION_CHANGE = "RAPID_LOCATION_CHANGE"
    CUSTOMER_RISK_HISTORY = "CUSTOMER_RISK_HISTORY"
    BANK_FAILURE_SPIKE = "BANK_FAILURE_SPIKE"
    PAYMENT_METHOD_FAILURE_SPIKE = "PAYMENT_METHOD_FAILURE_SPIKE"
    MERCHANT_FAILURE_SPIKE = "MERCHANT_FAILURE_SPIKE"
    REFUND_PATTERN = "REFUND_PATTERN"
    DUPLICATE_PAYMENT_PATTERN = "DUPLICATE_PAYMENT_PATTERN"
